import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { HonoAuthBridge } from "@/lib/hono-auth-bridge";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import QueryProviders from "@/providers/query-provider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const raleway = Raleway({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				geistMono.variable,
				"font-sans",
				raleway.variable,
			)}>
			<ClerkProvider>
				<body className="min-h-full flex flex-col">
					<QueryProviders>
						<ThemeProvider>
							{children}
							<Toaster />
							<HonoAuthBridge />
						</ThemeProvider>
					</QueryProviders>
				</body>
			</ClerkProvider>
		</html>
	);
}
